### ISSUE TITLE
how to fix it, where is my mistake, stormwall will try

### ISSUE THREAD

**Issue by Timezero1** [R00tS3c/Layer7-MultiBypass#5]
Error: Cannot find module 'request'
Require stack:
- /root/Рабочий стол/Layer7-MultiBypass-main/flood.js
- /root/Рабочий стол/Layer7-MultiBypass-main/method.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/Рабочий стол/Layer7-MultiBypass-main/flood.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Рабочий стол/Layer7-MultiBypass-main/flood.js',
    '/root/Рабочий стол/Layer7-MultiBypass-main/method.js'
  ]
}
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /root/Рабочий стол/Layer7-MultiBypass-main/flood.js
- /root/Рабочий стол/Layer7-MultiBypass-main/method.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/Рабочий стол/Layer7-MultiBypass-main/flood.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Рабочий стол/Layer7-MultiBypass-main/flood.js',
    '/root/Рабочий стол/Layer7-MultiBypass-main/method.js'
  ]

**Comment by R00tS3c** [comment]
npm install
