### ISSUE TITLE
The attack will not stop after time

### ISSUE THREAD

**Issue by bixinian** [R00tS3c/Layer7-MultiBypass#6]

**Comment by bixinian** [comment]
Error: options.uri is a required argument
    at Request.init (/var/www/html/node_modules/request/request.js:231:31)
    at new Request (/var/www/html/node_modules/request/request.js:127:8)
    at request (/var/www/html/node_modules/request/index.js:53:10)
    at /var/www/html/node_modules/request/index.js:100:12
    at Timeout.randomreq [as _onTimeout] (/var/www/html/flood.js:385:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by R00tS3c** [comment]
use pm2 or forever npm module :P
